name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up a Selenium Server
        run: npm install -g webdriver-manager

      - name: Update Selenium Server
        run: webdriver-manager update --standalone

      - name: Start Selenium Server
        run: webdriver-manager start --detach

      - name: Wait for Selenium Server to Start
        run: sleep 20 # Adjust the sleep duration based on your needs

      - name: Install dependencies
        run: |
          npm install
          npm install -g codeceptjs

      - name: Run CodeceptJS tests
        run: |
          npx codeceptjs run -g homepage
