name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Setting up a Selenium Server
        run: npm install -g webdriver-manager

      - name: Update Selenium Server
        run: webdriver-manager update

      - name: Start Selenium Server
        run: webdriver-manager start

      - name: Run tests
        run: npx codeceptjs run -g homepage
